version: '3.8'


services:

  postgres:
    container_name: pg_container
    image: postgres
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", '${POSTGRES_DB}']
      interval: 5s
      retries: 5
    restart: always
    ports:
      - ${POSTGRES_HTTP_PORT}:${POSTGRES_HTTP_PORT}
